# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise32"

  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.synced_folder "jobs/", "/mnt/jobs"
  config.vm.synced_folder "views/", "/mnt/views"

  config.vm.provision "shell", inline: <<-SHELL
    wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
    sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
    sudo apt-get update
    sudo apt-get -qy install jenkins curl

    sudo apt-get -qy install git
    for PLUGIN in git scm-api token-macro promoted-builds git-client parameterized-trigger build-pipeline-plugin jquery dashboard-view; do
      curl --silent --location http://updates.jenkins-ci.org/latest/${PLUGIN}.hpi -o /var/lib/jenkins/plugins/${PLUGIN}.hpi > /dev/null
      chown jenkins:jenkins /var/lib/jenkins/plugins/${PLUGIN}.hpi
    done

    sudo service jenkins restart

    echo "Waiting for Jenkins to come up"
    until $(curl --output /dev/null --silent --head --fail http://localhost:8080); do
      sleep 1
    done

    # Create or Update
    pushd .
    cd /mnt/jobs
    for JOB_CONFIG in *; do
      JOB_NAME=$( echo $JOB_CONFIG | sed s/.xml$// )
      curl --silent -X POST --data-binary "@/mnt/jobs/$JOB_CONFIG" -H "Content-Type: application/xml" "http://localhost:8080/createItem?name=$JOB_NAME" > /dev/null
      curl --silent -X POST --data-binary "@/mnt/jobs/$JOB_CONFIG" "http://localhost:8080/job/$JOB_NAME/config.xml" > /dev/null
    done
    cd /mnt/views
    for VIEW_CONFIG in *; do
      VIEW_NAME=$( echo $VIEW_CONFIG | sed s/.xml$// )
      curl --silent -X POST --data-binary "@/mnt/views/$VIEW_CONFIG" -H "Content-Type: application/xml" "http://localhost:8080/createView?name=$VIEW_NAME" > /dev/null
      curl --silent -X POST --data-binary "@/mnt/views/$VIEW_CONFIG" "http://localhost:8080/view/$VIEW_NAME/config.xml" > /dev/null
    done
    popd

    echo "Triggering builds"
    for I in 1 2 3 4 5; do
      curl --silent -X POST http://localhost:8080/job/Test/build > /dev/null
      # Wait for build to run to enqueue next
      sleep 10
    done
  SHELL
end
