# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise32"

  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.synced_folder "jobs/", "/mnt/jobs"

  config.vm.provision "shell", inline: <<-SHELL
    wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
    sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
    sudo apt-get update
    sudo apt-get -qy install jenkins curl
    # Create or Update
    curl --silent -X POST --data-binary @/mnt/jobs/Deploy.xml -H "Content-Type: application/xml" http://localhost:8080/createItem\?name\=Deploy > /dev/null
    curl --silent -X POST --data-binary @/mnt/jobs/Deploy.xml http://localhost:8080/job/Deploy/config.xml > /dev/null
    curl --silent -X POST --data-binary @/mnt/jobs/Test.xml -H "Content-Type: application/xml" http://localhost:8080/createItem\?name\=Test > /dev/null
    curl --silent -X POST --data-binary @/mnt/jobs/Test.xml http://localhost:8080/job/Test/config.xml > /dev/null

    echo "Triggering builds"
    for i in 1 2 3 4 5; do
      curl --silent -X POST http://localhost:8080/job/Test/build > /dev/null
      # Wait for build to run to enqueue next
      sleep 10
    done
  SHELL
end
