#!/bin/bash
set -eo pipefail

readonly VERSION="0.11.1"

buildviz_jar_name() {
    echo "buildviz-$1-standalone.jar"
}

fetch_buildviz_jar() {
    (
        cd buildviz
        if [[ ! -f $(buildviz_jar_name "$VERSION") ]]; then
            rm -f $(buildviz_jar_name "*")
            curl -LO "https://github.com/cburgmer/buildviz/releases/download/${VERSION}/buildviz-${VERSION}-standalone.jar"
        fi
    )
}

goal_build() {
    fetch_buildviz_jar
    docker-compose build
}

goal_publish() {
    docker-compose push
}

goal_logs() {
    docker-compose logs
}

goal_up() {
    fetch_buildviz_jar

    docker-compose up -d

    echo "Now point your browser to http://localhost:8080 ..."
    echo "Stop with $0 stop"
}

goal_down() {
    docker-compose down
}

ensure_ssh_identity_exists() {
    if ! ssh-add -l | grep "$HOME/.ssh/id_rsa " > /dev/null; then
        echo "Make sure the key uploaded to AWS is registered with ssh-add"
        exit 1
    fi
}

goal_tf() {
    ensure_ssh_identity_exists
    (
        cd deploy
        terraform init
        if [[ $# -eq 0 ]]; then
            terraform plan
        else
            terraform "$@"
        fi
    )
}

main() {
    local GOAL="$1"
    if type "goal_${GOAL}" > /dev/null 2>&1; then
        shift
        "goal_${GOAL}" "$@"
    else
        echo -n "Usage: $0 "
        set | grep -e "^goal_" | sed "s/^goal_\(.*\)().*/\1/" | xargs | sed "s/ / | /g"
        exit 1
    fi
}

main "$@"
