#!/bin/bash
set -eo pipefail

goal_build() {
    docker-compose build
}

goal_publish() {
    docker-compose push
}

goal_logs() {
    docker-compose logs
}

goal_up() {
    docker-compose up -d

    echo "Now point your browser to http://localhost:8080 ..."
    echo "Stop with $0 stop"
}

goal_down() {
    docker-compose down
}

ensure_ssh_identity_exists() {
    if ! ssh-add -l | grep "$HOME/.ssh/id_rsa " > /dev/null; then
        echo "Make sure the key uploaded to AWS is registered with ssh-add"
        exit 1
    fi
}

goal_tf() {
    ensure_ssh_identity_exists
    (
        cd deploy
        terraform init
        if [[ $# -eq 0 ]]; then
            terraform plan
        else
            terraform "$@"
        fi
    )
}

main() {
    local GOAL="$1"
    if type "goal_${GOAL}" > /dev/null 2>&1; then
        shift
        "goal_${GOAL}" "$@"
    else
        echo -n "Usage: $0 "
        set | grep -e "^goal_" | sed "s/^goal_\(.*\)().*/\1/" | xargs | sed "s/ / | /g"
        exit 1
    fi
}

main "$@"
