# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network :forwarded_port, guest: 8111, host: 8111
  config.vm.synced_folder "import/", "/mnt/import"
  config.vm.synced_folder "config/", "/mnt/config"
  config.vm.synced_folder "cache/", "/mnt/cache"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    SYNCED_IMPORT_DIR="/mnt/import"
    SYNCED_CACHE_DIR="/mnt/cache"

    sudo apt-get update
    sudo apt-get -qy install curl openjdk-8-jre ruby

    TEAMCITY_DIR=`pwd`/TeamCity
    if [ ! -d "$TEAMCITY_DIR" ]; then
        TEAMCITY_TAR_GZ="TeamCity-2017.2.4.tar.gz"
        TEAMCITY_DOWNLOAD="${SYNCED_CACHE_DIR}/${TEAMCITY_TAR_GZ}"
        if [ ! -f "$TEAMCITY_DOWNLOAD" ]; then
            echo "Downloading TeamCity..."
            curl -L --silent "https://download.jetbrains.com/teamcity/${TEAMCITY_TAR_GZ}" -o "$TEAMCITY_DOWNLOAD"
        fi
        tar -zxf "$TEAMCITY_DOWNLOAD"
    fi

    echo "Setting up startup..."
    sudo cp /mnt/config/*.service /lib/systemd/system
    sudo systemctl enable teamcity-agent
    sudo systemctl enable teamcity-server

    echo "Setting up project..."
    PROJECT_CONFIG_DIR="/root/.BuildServer/config/projects"
    mkdir -p "$PROJECT_CONFIG_DIR"
    cd "$SYNCED_IMPORT_DIR"
    for PROJECT in *; do
        sudo cp -R "$SYNCED_IMPORT_DIR/$PROJECT" "$PROJECT_CONFIG_DIR"
    done
    cd - > /dev/null

    echo "Starting TeamCity agent and server..."
    sudo service teamcity-agent start
    sudo service teamcity-server start
  SHELL
end
